/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import java.util.ArrayList;
import java.util.List;
import model.Consumible;
import model.Modelo;
import views.BaseSingleView;

/**
 *
 * @author kevin
 */
public class formConsumible extends BaseSingleView<Consumible> {

    private List<Modelo> ModeloList = null;
    
    /**
     * Creates new form formConsumible
     */
    public formConsumible() {
        initComponents();
        this.saveBtn = this.btnGuardar;
        this.cancelBtn = this.btnCancelar;
        this.setModel(this.model);
    }

    public void loadModelo(List<Modelo> list) {
        this.ModeloList = new ArrayList<>();
        this.cbxModelo.removeAllItems();
        list.forEach((data) -> {
            if(data.getTipo().getClase()){
                this.ModeloList.add(data);
                this.cbxModelo.addItem(data.getTipo().getNombre() + " - " + data.getNombre() + " (" + data.getMarca().getNombre() + ")");
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tbxCategoria = new javax.swing.JTextField();
        tbxTipo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tbxMarca = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cbxModelo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chbxEstado = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        tbxCantidad = new javax.swing.JFormattedTextField();
        tbxCantidadMinima = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Registrar Consumible");

        jLabel2.setText("Categoría");

        jLabel3.setText("Tipo");

        tbxCategoria.setText("jTextField1");

        tbxTipo.setText("jTextField1");

        jLabel4.setText("Marca");

        tbxMarca.setText("jTextField1");

        jLabel5.setText("Modelo");

        cbxModelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbxModelo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxModeloItemStateChanged(evt);
            }
        });

        jLabel6.setText("Cantidad Actual");

        jLabel7.setText("Cantidad Mínima");

        jLabel8.setText("Estado");

        chbxEstado.setText("Activo");

        btnGuardar.setText("Guardar");

        btnCancelar.setText("Cancelar");

        tbxCantidad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        tbxCantidadMinima.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getIntegerInstance())));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(86, 86, 86)
                                .addComponent(btnCancelar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(108, 108, 108)
                                .addComponent(chbxEstado))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(122, 122, 122)
                                .addComponent(tbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbxCantidadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbxCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tbxCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tbxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tbxMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbxModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tbxCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tbxCantidadMinima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(chbxEstado))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxModeloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxModeloItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == 1){
            int position = this.cbxModelo.getSelectedIndex();
            Modelo modelo = this.ModeloList.get(position);
            this.tbxCategoria.setText(modelo.getTipo().getCategoria().getNombre());
            this.tbxTipo.setText(modelo.getTipo().getNombre());
            this.tbxMarca.setText(modelo.getMarca().getNombre());
        } else {
            this.tbxCategoria.setText("");
            this.tbxTipo.setText("");
            this.tbxMarca.setText("");
        }
    }//GEN-LAST:event_cbxModeloItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formConsumible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formConsumible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formConsumible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formConsumible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formConsumible().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox<String> cbxModelo;
    private javax.swing.JCheckBox chbxEstado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JFormattedTextField tbxCantidad;
    private javax.swing.JFormattedTextField tbxCantidadMinima;
    private javax.swing.JTextField tbxCategoria;
    private javax.swing.JTextField tbxMarca;
    private javax.swing.JTextField tbxTipo;
    // End of variables declaration//GEN-END:variables

    @Override
    public Consumible getModel() {
        if(this.model == null)
            this.model = new Consumible(0);
        this.model.setModelo(this.ModeloList.get(this.cbxModelo.getSelectedIndex()));
        this.model.setCantidad(Integer.parseInt(this.tbxCantidad.getText()));
        this.model.setCantidad_minima(Integer.parseInt(this.tbxCantidadMinima.getText()));
        this.model.setEstado(this.chbxEstado.isSelected());
        return this.model;
    }

    @Override
    public void setModel(Consumible model) {
        this.model = model;
        this.tbxCategoria.setText(this.model != null ? this.model.getModelo().getTipo().getCategoria().getNombre() : "");
        this.tbxTipo.setText(this.model != null ? this.model.getModelo().getTipo().getNombre(): "");
        this.tbxMarca.setText(this.model != null ? this.model.getModelo().getMarca().getNombre() : "");
        this.cbxModelo.setSelectedItem(this.ModeloList != null && this.model != null ? this.model.getModelo().getNombre() : "");
        this.tbxCantidad.setText(this.model != null ? Integer.toString(this.model.getCantidad()) : "");
        this.tbxCantidadMinima.setText(this.model != null ? Integer.toString(this.model.getCantidad_minima()) : "");
        this.chbxEstado.setSelected(this.model != null ? this.model.getEstado(): false);
    }

    @Override
    public boolean checkView() {
        if(this.cbxModelo.getSelectedItem().toString().equals(""))
            this.addError("modelo", "El modelo es obligatorio.");
        if(!this.tbxCantidad.getText().equals("") && Integer.parseInt(this.tbxCantidad.getText()) < 0)
            this.addError("cantidad", "La cantidad actual debe ser mayor o igual a cero.");
        if(this.tbxCantidadMinima.getText().equals(""))
            this.addError("cantidad_minima", "La cantidad mínima es obligatoria.");
        else if(Integer.parseInt(this.tbxCantidadMinima.getText()) <= 0)
                this.addError("cantidad_minima", "La cantidad mínima debe ser mayor que cero.");
        return this.hasErrors();
    }

    @Override
    public boolean isNew() {
        return this.model == null || this.model.getId() == 0;
    }
    
}