/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import controllers.ActivoController;
import controllers.AreaController;
import controllers.CategoriaController;
import controllers.ConsumibleController;
import controllers.MarcaController;
import controllers.ModeloElementoController;
import controllers.OrdenCompraController;
import controllers.ProveedorController;
import controllers.TipoElementoController;
import controllers.TrabajadorController;
import controllers.TurnoController;
import daos.IDaoFactory;

/**
 *
 * @author kevin
 */
public class main extends javax.swing.JFrame {

    public static IDaoFactory getDaoFactory(){
        return null; //DaoFactory.getInstance(DB_Motor.SQLite);
    }
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEntradas = new javax.swing.JButton();
        btnEntregas = new javax.swing.JButton();
        btnActivos = new javax.swing.JButton();
        btnConsumibles = new javax.swing.JButton();
        btnCategorias = new javax.swing.JButton();
        btnTiposElementos = new javax.swing.JButton();
        btnMarcas = new javax.swing.JButton();
        btnModelosElementos = new javax.swing.JButton();
        btnTrabajadores = new javax.swing.JButton();
        btnAreas = new javax.swing.JButton();
        btnTurnos = new javax.swing.JButton();
        btnProveedores = new javax.swing.JButton();
        btnOrdenesCopra = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnEntradas.setText("Entradas");
        btnEntradas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntradasMouseClicked(evt);
            }
        });

        btnEntregas.setText("Entregas");
        btnEntregas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEntregasMouseClicked(evt);
            }
        });

        btnActivos.setText("Activos");
        btnActivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnActivosMouseClicked(evt);
            }
        });

        btnConsumibles.setText("Consumibles");
        btnConsumibles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConsumiblesMouseClicked(evt);
            }
        });

        btnCategorias.setText("Categorías");
        btnCategorias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCategoriasMouseClicked(evt);
            }
        });

        btnTiposElementos.setText("Tipos de Elementos");
        btnTiposElementos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTiposElementosMouseClicked(evt);
            }
        });

        btnMarcas.setText("Marcas");
        btnMarcas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMarcasMouseClicked(evt);
            }
        });

        btnModelosElementos.setText("Modelos de Elementos");
        btnModelosElementos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModelosElementosMouseClicked(evt);
            }
        });

        btnTrabajadores.setText("Trabajadores");
        btnTrabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrabajadoresMouseClicked(evt);
            }
        });

        btnAreas.setText("Áreas");
        btnAreas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAreasMouseClicked(evt);
            }
        });

        btnTurnos.setText("Turnos");
        btnTurnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTurnosMouseClicked(evt);
            }
        });

        btnProveedores.setText("Proveedores");
        btnProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProveedoresMouseClicked(evt);
            }
        });

        btnOrdenesCopra.setText("Ordenes de Compra");
        btnOrdenesCopra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOrdenesCopraMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEntregas)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEntradas)
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnActivos)
                                    .addComponent(btnConsumibles))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTrabajadores)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnTurnos)
                                            .addComponent(btnAreas)
                                            .addComponent(btnProveedores)
                                            .addComponent(btnOrdenesCopra))))))
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModelosElementos)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(btnMarcas))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCategorias)
                                    .addComponent(btnTiposElementos))))))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntradas)
                    .addComponent(btnActivos)
                    .addComponent(btnTrabajadores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsumibles)
                    .addComponent(btnAreas))
                .addGap(5, 5, 5)
                .addComponent(btnEntregas)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(btnCategorias))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTurnos)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnTiposElementos))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnProveedores)))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMarcas)
                    .addComponent(btnOrdenesCopra))
                .addGap(37, 37, 37)
                .addComponent(btnModelosElementos)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntradasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntradasMouseClicked
        // TODO add your handling code here:
        new formEntradas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEntradasMouseClicked

    private void btnEntregasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEntregasMouseClicked
        // TODO add your handling code here:
        new formEntregas().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEntregasMouseClicked

    private void btnActivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnActivosMouseClicked
        // TODO add your handling code here:
        ActivoController ActivoController = new ActivoController(this);
    }//GEN-LAST:event_btnActivosMouseClicked

    private void btnConsumiblesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConsumiblesMouseClicked
        // TODO add your handling code here:
        ConsumibleController consumibleController = new ConsumibleController(this);
    }//GEN-LAST:event_btnConsumiblesMouseClicked

    private void btnCategoriasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCategoriasMouseClicked
        // TODO add your handling code here:
        CategoriaController categoriaController = new CategoriaController(this);
    }//GEN-LAST:event_btnCategoriasMouseClicked

    private void btnTiposElementosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTiposElementosMouseClicked
        // TODO add your handling code here:
        TipoElementoController tipoElementoController = new TipoElementoController(this);
    }//GEN-LAST:event_btnTiposElementosMouseClicked

    private void btnMarcasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMarcasMouseClicked
        // TODO add your handling code here:
        MarcaController marcaController = new MarcaController(this);
    }//GEN-LAST:event_btnMarcasMouseClicked

    private void btnModelosElementosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModelosElementosMouseClicked
        // TODO add your handling code here:
        ModeloElementoController modeloElementoController = new ModeloElementoController(this);
    }//GEN-LAST:event_btnModelosElementosMouseClicked

    private void btnTrabajadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrabajadoresMouseClicked
        // TODO add your handling code here:
        TrabajadorController trabajadorController = new TrabajadorController(this);
    }//GEN-LAST:event_btnTrabajadoresMouseClicked

    private void btnAreasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAreasMouseClicked
        // TODO add your handling code here:
        AreaController areaController = new AreaController(this);
    }//GEN-LAST:event_btnAreasMouseClicked

    private void btnTurnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTurnosMouseClicked
        // TODO add your handling code here:
        TurnoController turnoController = new TurnoController(this);
    }//GEN-LAST:event_btnTurnosMouseClicked

    private void btnProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProveedoresMouseClicked
        // TODO add your handling code here:
        ProveedorController proveedorController = new ProveedorController(this);
    }//GEN-LAST:event_btnProveedoresMouseClicked

    private void btnOrdenesCopraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrdenesCopraMouseClicked
        // TODO add your handling code here:
        OrdenCompraController ordenCompraController = new OrdenCompraController(this);
    }//GEN-LAST:event_btnOrdenesCopraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivos;
    private javax.swing.JButton btnAreas;
    private javax.swing.JButton btnCategorias;
    private javax.swing.JButton btnConsumibles;
    private javax.swing.JButton btnEntradas;
    private javax.swing.JButton btnEntregas;
    private javax.swing.JButton btnMarcas;
    private javax.swing.JButton btnModelosElementos;
    private javax.swing.JButton btnOrdenesCopra;
    private javax.swing.JButton btnProveedores;
    private javax.swing.JButton btnTiposElementos;
    private javax.swing.JButton btnTrabajadores;
    private javax.swing.JButton btnTurnos;
    // End of variables declaration//GEN-END:variables
}
